### ISSUE TITLE
Man Pages are Barred From Installation

### ISSUE THREAD

**Issue by naftulikay** [naftulikay/docker-centos-vm#7]
For solution, see here: https://unix.stackexchange.com/questions/259478/cant-install-man-pages-on-minimal-centos-docker-container#270615

**Comment by naftulikay** [comment]
Essentially this wants this step:

```
sed -i '/tsflags=nodocs/d' /etc/yum.conf
```

I need to basically do a `yum reinstall *` to include man pages for every package.

**Comment by ninrod** [comment]
does this work: `yum reinstall *`?

**Comment by naftulikay** [comment]
@ninrod Can you try it out? Not trying to be a troll, but I'm pretty busy right now. If that works, I'll add it into the Dockerfile.

**Comment by ninrod** [comment]
@naftulikay no problem. I've tried it out, it does not work. 

maybe `yum list installed | awk '{print $1}' | xargs yum reinstall` is the way to go.

**Comment by naftulikay** [comment]
@ninrod lol haha, at least we have an answer then; PRs welcome. Dealing with another fire and a bug in Ansible right now.

**Comment by naftulikay** [comment]
Working in [naftulikay/docker-centos7-vm](https://github.com/naftulikay/docker-centos7-vm).
